[package]
name = "remove_health_check_entry"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { version = "0.1.0", path = "../common" }
config.workspace = true
sqlx.workspace = true
tokio.workspace = true
