services:
  task-db:
    image: postgres
    container_name: task-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: tasks
      POSTGRES_HOST: localhost
