services:
  task-db:
    container_name: task-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
      POSTGRES_HOST: localhost
  health-check-db:
    container_name: health-check 
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_checks 
      POSTGRES_HOST: localhost


