# create a file called screts.yaml
# put these values into secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: health-check-secrets
type: Opaque
data:
  APP__HEALTH_CHECK__DATABASE_DB: aGVhbHRoLWNoZWNrcy1kYg==
  APP__HEALTH_CHECK__DATABASE_HOST: aGVhbHRoLWNoZWNrcy1kYi1zdmM=
  APP__HEALTH_CHECK__DATABASE_PASSWORD: cGFzc3dvcmQ=
  APP__HEALTH_CHECK__DATABASE_PORT: NTQzMg== 
  APP__HEALTH_CHECK__DATABASE_USER: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: tasks-secrets
type: Opaque
data:
  APP__TASKS__DATABASE_DB: dGFza3M=
  APP__TASKS__DATABASE_HOST: dGFza3MtZGItc3Zj
  APP__TASKS__DATABASE_PASSWORD: cGFzc3dvcmQ= 
  APP__TASKS__DATABASE_PORT: NTQzMg== 
  APP__TASKS__DATABASE_USER: cG9zdGdyZXM=


---
apiVersion: v1
kind: Secret
metadata:
  name: sqs-secrets
type: Opaque
data:
  APP__SQS__ACCESS_KEY: 
  APP__SQS__QUEUE: 
  APP__SQS__QUEUE_URL: 
  APP__SQS__REGION: 
  APP__SQS__SECRET_KEY: 

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
type: Opaque
data:
  APP__S3__ACCESS_KEY: 
  APP__S3__BUCKET: 
  APP__S3__REGION: 
  APP__S3__SECRET_KEY: 

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  APP__JWT_SECRET: 
