#!/bin/sh

echo "Running cargo sqlx prepare --workspace..."

cargo sqlx prepare --workspace

if [ $? -ne 0 ]; then
  echo "cargo sqlx prepare failed. Aborting commit."
  exit 1
fi

echo "cargo sqlx prepare completed successfully."
