app: pub-api
deployment:
  enable: true
  replicas: 2
  metadata:
    name: pub_api_deployment
service:
  enable: true
  port: 80
  targetPort: 3000
  type: LoadBalancer
containers:
    image: pradeep800/pub_api:latest
    containerPort: 3000
secrets:
  - tasks-secrets
  - s3-secrets
# no cron job
cron_job:
  enable: false 
