app: pub-api
deployment:
  replicas: 2
service:
  port: 80
  targetPort: 3000
  type: LoadBalancer
containers:
    image: pradeep800/pub_api:latest
    containerPort: 3000
secrets:
  - tasks-secrets
  - s3-secrets
