app: status-check
deployment:
  replicas: 2
service:
  port: 80
  targetPort: 4000 
  type: ClusterIP 
containers:
    image: pradeep800/status_check:latest
    containerPort: 4000 
secrets:
  - tasks-secrets
  - health-check-secrets 
  - jwt-secrets

