app: status-check
deployment:
  enable: true
  replicas: 2
service:
  enable: true
  port: 80
  targetPort: 4000 
  type: ClusterIP 
containers:
    image: pradeep800/status_check:latest
    containerPort: 4000 
secrets:
  - tasks-secrets
  - health-check-secrets 
  - jwt-secrets
cron_job:
  enable: false 
postgres_statefulset:
  enable: false
volume:
  enable: false
