app: tasks_producer
deployment:
  enable: true
  replicas: 2
  metadata:
    name: tasks_producer_deployment 
service:
  enable: false 
containers:
    image: pradeep8b0/tasks_producer:latest
secrets:
  - tasks-secrets
  - sqs-secrets 
cron_job:
  enable: false
