app: tasks-db 
service:
  port: 5432 
  targetPort: 5432 
  type: ClusterIP
containers:
  image: postgres:latest
  containerPort: 5432 
postgres_statefulset:
  replicas: 1
volume:
  size: 500Mi 
env:
  POSTGRES_DB: tasks 
  POSTGRES_USER: postgres 
  POSTGRES_PASSWORD: password 
