name: Publish worker main 
on:
  [workflow_dispatch]

env:
  file_name: "worker_main"
jobs:
  publish_image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Build Docker image
        run: |
          docker build . -t pradeep800/${{ env.file_name }}:${{ steps.slug.outputs.sha7 }} -f ./services/worker/main/Dockerfile
          docker tag pradeep800/${{ env.file_name }}:${{ steps.slug.outputs.sha7 }} pradeep800/${{ env.file_name }}:latest
      
      - name: Publish Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u pradeep800 --password-stdin
          docker push pradeep800/${{ env.file_name }}:${{ steps.slug.outputs.sha7 }}
          docker push pradeep800/${{ env.file_name }}:latest  
