{{- if .Values.cron_job.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-10-minutes
spec:
  schedule: "*/10 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.app}} 
            image: {{.Values.cron_job.image}} 
          restartPolicy: OnFailure
{{-  end }}
