{{- if .Values.cron_job.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Values.app}}
spec:
  schedule: "*/10 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.app}}
            image: {{.Values.cron_job.image}} 
{{ include "helpers.list-env-variables" . | indent 12 }}
          restartPolicy: OnFailure
{{-  end }}
