{{- if .Values.deployment}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app}}-deployment
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
       {{- if .Values.service_account}}
      serviceAccountName: {{.Values.service_account.name}} 
       {{- end}}
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.containers.image }}
        {{- if .Values.containers.containerPort }}
        ports:
        - containerPort: {{ .Values.containers.containerPort }}
        {{- end }}  
{{ include "helpers.list-env-variables" . | indent 8 }}
{{- end }}
