{{- if .Values.deployment.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app}}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.containers.image }}
        {{- if .Values.containers.containerPort }}
        ports:
        - containerPort: {{ .Values.containers.containerPort }}
        {{- end }}  
{{ include "helpers.list-env-variables" . | indent 8 }}
{{- end }}  
