{{- if .Values.postgres_statefulset.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.app}}-statefulset 
spec:
  serviceName: {{ .Values.app }}-svc
  replicas: {{ .Values.postgres_statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.containerPort }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.env.POSTGRES_PASSWORD }}
        volumeMounts:
        - name: postgres-vol 
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-vol 
        persistentVolumeClaim:
          claimName: {{ .Values.app}}-volumne
{{- end }}
