apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-svc
spec:
  type: {{.Values.service.type}} 
  selector:
    app: {{.Values.app}} 
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}} 
