{{- if .Values.service_account}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.service_account.name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.service_account.name}}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.service_account.name}}
subjects:
- kind: ServiceAccount
  name: {{.Values.service_account.name}}
roleRef:
  kind: Role
  name: {{.Values.service_account.name}}
  apiGroup: rbac.authorization.k8s.io
{{- end}}
