{{- if .Values.volume}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app}}-volumne
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
{{- end}}
